main/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user_example.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('todo/', include('todo.urls')),
]

todo/urls.py
from django.urls import path
from .views import (
    TodoList,
    TodoCreate,
    TodoListCreate,
    is_completed,
    TodoUpdate,
    TodoDelete,
)

# views'e uğramadan direkt List:
from django.views.generic import ListView
from .models import Todo

app_name = 'todo'

urlpatterns = [
    
    # views'e uğramadan direkt List:
    path('list_direct/', ListView.as_view(model=Todo, context_object_name='todos'), name='list_direct'),

    # class_base home List;
    path('list/', TodoList.as_view(), name='list'),

    # class_base home Create;
    path('add/', TodoCreate.as_view(), name='add'),

    # class_base home (List/Create);
    path('', TodoListCreate.as_view(), name='home'),
    
    path('isdone/<int:id>', is_completed, name='done'),
    
    # path('update/<int:id>', todo_update, name='update'),
    path('update/<int:id>', TodoUpdate.as_view(), name='update'),
    
    # path('delete/<int:id>', todo_delete, name='delete'),
    path('delete/<int:id>', TodoDelete.as_view(), name='delete'),
]

user_example/urls.py
from django.urls import path
from .views import (
    home,
    register,
    special,
)
from django.contrib.auth import views as auth_views

app_name = 'user_example'

urlpatterns = [
    path('', home, name='home'),
    path('register/', register, name='register'),
    
    # custom password_chage view and template
    path('password_change/', auth_views.PasswordChangeView.as_view(
        template_name="registration/password_change.html"), name="password_change"),
    
    path('special/', special, name='special'),
    
    # custom logout view and redirect
    # path('logout/', auth_views.LogoutView.as_view(next_page='home'), name='logout'),
    
]

todo/models.py
from django.db import models

# Create your models here.


status_choices = [
    ('C', 'Complited'),
    ('P', 'Pending'),
    ('I', 'In-Progress'),
]

priority_choices = [
    ('1', '1️⃣'),
    ('2', '2️⃣'),
    ('3', '3️⃣'),
    ('4', '4️⃣'),
    ('5', '5️⃣'),
]

class Todo(models.Model):
    title = models.CharField(max_length=70)
    description = models.TextField()
    is_done = models.BooleanField(default=False)
    status = models.CharField(max_length=2, choices=status_choices)
    priority = models.CharField(max_length=2, choices=priority_choices)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.title

user_example/models.py
from django.db import models

# Create your models here.

todo/forms.py
from django import forms
from .models import Todo

class TodoForm(forms.ModelForm):
    class Meta:
        model = Todo
        fields = "__all__"
    

todo/views.py
from django.shortcuts import render, redirect
from .models import Todo
from .forms import TodoForm
from django.contrib import messages

# for class based views import;
from django.views.generic import (
    ListView,
    CreateView,
    UpdateView,
    DeleteView,
)
from django.urls import reverse_lazy


class TodoList(ListView):
    model = Todo
    # default context_object_name: APP_Name_list (todo_list)
    context_object_name = 'todos'
    # template_name = "todo/home.html" or 
    # default template_name = "todo/todo_list.html"
    # ordering = ['priority', ]
    ordering = ['-priority', ]


class TodoCreate(CreateView):
    model = Todo
    form_class = TodoForm 
    template_name = 'todo/todo_add.html'
    # default todo/todo_form.html
    success_url = reverse_lazy('todo:list')


class TodoListCreate(CreateView):
    model = Todo
    form_class = TodoForm 
    template_name = 'todo/home.html'
    success_url = reverse_lazy('todo:home')

    def get_context_data(self, **kwargs):
        kwargs['todos'] = Todo.objects.order_by('-priority')
        kwargs['done_count'] = Todo.objects.filter(is_done=True).count()
        kwargs['priority_count'] = Todo.objects.filter(priority__gt=2).count()
        return super(TodoListCreate, self).get_context_data(**kwargs)

    
def is_completed(request, id):
    todo = Todo.objects.get(id=id)
    todo.is_done = not(todo.is_done)
    todo.save()
    return redirect('todo:home')

    
class TodoUpdate(UpdateView):
    model = Todo
    form_class = TodoForm
    template_name = 'todo/todo_update.html'
    # default temp_name "todo/todo_update_form.html"
    pk_url_kwarg = 'id'
    # default pk_url_kwargs = 'pk'
    success_url = reverse_lazy('todo:home')


class TodoDelete(DeleteView):
    model = Todo
    template_name = 'todo/todo_delete.html'
    # default temp_name "todo/todo_update_form.html"
    pk_url_kwarg = 'id'
    # default pk_url_kwargs = 'pk'
    success_url = reverse_lazy('todo:home')

user_example/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required


# Create your views here.
def home(request):
    return render(request, 'user_example/index.html')

#! register -> login edip -> home page 
# def register(request):
#     form = UserCreationForm(request.POST or None)
#     if form.is_valid():
#         form.save()
#         username = form.cleaned_data.get("username")
#         password = form.cleaned_data.get("password1")
#         user = authenticate(username = username, password = password)
#         # return redirect('user_example:login')
#         login(request, user)
#         return redirect('user_example:home')
#     context = {
#         'form': form
#     }
#     return render(request, 'registration/register.html', context)

#! register -> login page 
def register(request):
    form = UserCreationForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('login')
    context = {
        'form': form
    }
    return render(request, 'registration/register.html', context)


# @login_required
def special(request):
    return render(request, 'user_example/special.html')

todo/templates/todo/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'todo/css/stylee.css' %}">
    
    <!-- title block -->
    <title> Todo App - {% block title %} {% endblock title %} </title>

</head>
<body>
    
    <!-- navbar start -->
    <nav class="navbar navbar-expand-lg navbar navbar-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="/">
            <img src="{% static 'todo/images/cw_logo.png' %}" alt="Hi!" width="45" height="45">Umit_Developer Todo App</a>
        </div>
        <div class="col-auto ms-auto">
            {% if user.is_authenticated %}
            <div class="d-flex">
                <form method="POST" action="{% url 'logout' %}">
                    {% csrf_token %}
                    <button type="submit">Logout</button>
                </form>
          
                <a href="{% url 'user_example:password_change' %}"><input type="submit" value="Password Change"></a>
        
                {% comment %}
                <a href="{% url 'user_example:special' %}"><input type="submit" value="Special"></a>
                {% endcomment %}
            </div>
            {% else %}
            
            {% comment %}   
            <a href="{% url 'login' %}">Login</a> 
            {% endcomment %}
            
            <a href="{% url 'login' %}"><input type="submit" value="Login"></a> 
            
            <a href="{% url 'user_example:register' %}"><input type="submit" value="Register"></a> 
            
            <a href="{% url 'password_reset' %}"><input type="submit" value="I forget my password"></a> 
            
            {% comment %}
            <a href="{% url 'user_example:special' %}"><input type="submit" value="Special"></a>
            {% endcomment %}
                
            
            {% endif %}
            
        </div>
        
    </nav>

    <!-- messages -->
    {% if messages %} 
        {% for message in messages %} 
            {% if message.tags == "warning" %}
                <div id="warning" class="message">{{ message }}</div>
            {% else %}
                <div id="success" class="message">{{ message }}</div>
            {% endif %} 
        {% endfor %} 
    {% endif %}
    
    <!-- content block -->
    {% block content %}
    
    {% endblock content %}


    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="{% static 'todo/js/timeout.js' %}"></script>

</body>
</html>

todo/templates/todo/home.html
{% extends "todo/base.html" %}

{% block title %} Home {% endblock title %}


{% block content %}

{% if user.is_authenticated %}

<div class="container pt-4">
  <div class="row mt-2 p-0">

    <div class="col-lg-4 mx-auto p-0 shadow">
      <div class="alert alert-warning text-center">
        <h2>Add ToDo</h2>
      </div>
    <div class="p-4">
      {% load crispy_forms_tags %}
      <form action="" method="POST">
        {% csrf_token %} {% comment %} {{ form.as_p }} {% endcomment %} {{ form | crispy }}
          <hr>
          <input type="submit" value="ADD" class="btn btn-success">
      </form>
    </div>
  </div>

  <div class="col">
    <div class="border">
      {% if todos|length == 0 %}
      <div class="p-4">
        <br>
        <br>
        <div class="alert alert-danger text-center">
          <p class="" style="font-size: 30px;">ToDo Lists</p>
        </div>
        <br>
        <br>
      </div>
      {%else%}
      <div class="p-2">
        <table class="table table-hover">
          <thead>
            <tr>
              <th>No</th>
              <th>Title</th>
              <th>Is_Done?</th>
              <th>Status</th>
              <th>Priority</th>
              <th>Delete</th>
              <th>Update</th>
            </tr>
          </thead>
          <tbody>
            {% for todo in todos%}
              <tr>
                <td>{{forloop.counter}}</td>
                <td>{{todo.title}}</td>

                {% if todo.is_done == True %}
                  <td>
                    <a href="{% url 'todo:done' todo.id %}">✅</a>
                  </td>
                {% else %}
                  <td>
                    <a href="{% url 'todo:done' todo.id %}">💤</a>
                  </td>
                {% endif %}

                {% if todo.status == 'C'%}
                  <td>
                    ✅
                  </td>
                {% elif todo.status == 'I'%}
                  <td>
                    🚧
                  </td>
                {% elif todo.status == 'P'%}
                  <td>
                    💤
                  </td>
                {%endif%}
                
                <td>
                  {% if todo.priority == '1'%}
                    1️⃣
                  {%elif todo.priority == '2'%}
                    2️⃣
                  {%elif todo.priority == '3'%}
                    3️⃣
                  {%elif todo.priority == '4'%}
                    4️⃣
                  {%elif todo.priority == '5'%}
                    5️⃣
                  {%endif%}
                </td>
                <td>
                  <a href="{% url 'todo:delete' todo.id %}" target="_blank" title="Delete" class="">🗑️</a> 
                </td>
                <td>
                  <a href="{% url 'todo:update' todo.id %}" target="_blank"  class="">⚙️</a> 
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
      {%endif%}
    </div>

        <div class="col-lg-10 mx-auto p-0 pt-1 mt-1 shadow text-end alert alert-info text-secondary fw-bolder fs-6 fst-italic">
          <div class="p-1 m-2">
            <p>Tamamlanan Todo'ların sayısı : <span class="alert alert-danger p-1">{{done_count}} / {{todos | length}}</span></p>
          </div>
          <div class="p-1 m-2 pb-0">
            <p>Priority'si 2'den büyük olan Todo'ların sayısı : <span class="alert alert-danger p-1">{{priority_count}} / {{todos | length}}</span></p>
          </div>
        </div>


        <!-- Yan yana iki eşit parça -->
<div class="col-lg-10 mx-auto mt-3">
  <div class="row">
    <div class="col-lg-3 me-auto">
      <div class="p-2 text-center">
      <a href="{% url 'todo:list' %}" class="btn btn-danger btn-outline-light">To List</a>
      </div>
    </div>
    <div class="col-lg-3 ms-auto">
      <div class="p-2 text-center">
      <a href="{% url 'todo:add' %}" class="btn btn-danger btn-outline-light">To Add</a>
      </div>
    </div>
  </div>
</div>



      
  
  </div>
</div>

{% else %}
<div class="d-flex justify-content-center align-items-center" style="height: 200px;">
  <a href="{% url 'login' %}" class="btn btn-success btn-lg">Go to TODO page</a>
</div>
{% endif %}

{% endblock content %}

todo/templates/todo/todo_add.html
{% extends 'todo/base.html' %}

{% block title %} Add {% endblock title %}

{% block content %}

<div class="container pt-4">
    <div class="col-lg-6 mx-auto p-0 shadow">
      <div class="alert alert-warning text-center">
        <h2>Add Todo</h2>
      </div>
  
      <div class="p-4 d-flex align-items-center">
        {% load crispy_forms_tags %}
        <form action="" method="post">
          {% csrf_token %} {% comment %} {{ form.as_p }} {% endcomment %} {{ form | crispy }}
          <input type="submit" value="Add" class="btn btn-success" />
          <a href="{% url 'todo:home' %}"
            ><input type="button" value="CANCEL" class="btn btn-danger btn-outline-light"
          /></a>
        </form>
      </div>
    </div>
  </div>

{% endblock content %}

todo/templates/todo/todo_delete.html
{% extends 'todo/base.html' %}

{% block title %} Delete {% endblock title %}

{% block content %}
    
<div class="container pt-4">
  <div class="col-lg-6 mx-auto p-0 shadow">
    <div class="alert alert-warning text-center">
      <h2>Delete Todo</h2>
    </div>
    <div class="p-4 d-flex align-items-center">
      <form action="" method="post">
        {% csrf_token %}
        Are you sure delete <span>{{ todo }}</span> ?
        <input type="submit" value="Delete" class="btn btn-danger" />
        <a href="{% url 'todo:home' %}"><input type="button" value="CANCEL" class="btn btn-primary"></a>
      </form>
    </div>  
  </div>
</div>

{% endblock content %}
    

todo/templates/todo/todo_list.html
{% extends "todo/base.html" %}

{% block title %} Todos {% endblock title %}

{% block content %}

<!-- add button -->

<div class="col-lg-1 mx-auto p-1 mt-3 d-flex justify-content-center">
  <a href="{% url 'todo:add' %}" target="_blank" class="mx-2">
      <input type="submit" value="ADD TODO" class="btn btn-danger btn-outline-light">
  </a>
  <a href="{% url 'todo:home' %}" class="mx-2">
      <input type="submit" value="TODO HOME" class="btn btn-danger btn-outline-light">
  </a>
</div>


<div class="container pt-4">

  <div class="col">
    <div class="border">
      {% if todos|length == 0 %}
      <div class="p-4">
        <br>
        <br>
        <div class="alert alert-danger text-center">
          <p class="" style="font-size: 30px;">ToDo Lists</p>
        </div>
        <br>
        <br>
      </div>
      {%else%}
      <div class="p-2">
        <table class="table table-hover">
          <thead>
            <tr>
              <th>No</th>
              <th>Title</th>
              <th>Is_Done?</th>
              <th>Status</th>
              <th>Priority</th>
              <th>Delete</th>
              <th>Update</th>
            </tr>
          </thead>
          <tbody>
            {% for todo in todos%}
              <tr>
                <td>{{forloop.counter}}</td>
                <td>{{todo.title}}</td>
                
                {% if todo.is_done == True %}
                  <td>
                    ✅
                  </td>
                {% else %}
                  <td>
                    💤
                  </td>
                {% endif %}

                {% if todo.status == 'C'%}
                  <td>
                    ✅
                  </td>
                {% elif todo.status == 'I'%}
                  <td>
                    🚧
                  </td>
                {% elif todo.status == 'P'%}
                  <td>
                    💤
                  </td>
                {%endif%}
                <td>
                  {% if todo.priority == '1'%}
                    1️⃣
                  {%elif todo.priority == '2'%}
                    2️⃣
                  {%elif todo.priority == '3'%}
                    3️⃣
                  {%elif todo.priority == '4'%}
                    4️⃣
                  {%elif todo.priority == '5'%}
                    5️⃣
                  {%endif%}
                </td>
                <td>
                  <a href="{% url 'todo:delete' todo.id %}" target="_blank" title="Delete" class="">🗑️</a> 
                </td>
                <td>
                  <a href="{% url 'todo:update' todo.id %}" target="_blank"  class="">⚙️</a> 
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
      {%endif%}
    </div>

  </div>

</div>

{% endblock content %}

todo/templates/todo/todo_update.html
{% extends 'todo/base.html' %}

{% block title %} Update {% endblock title %}

{% block content %}

<div class="container pt-4">
  <div class="col-lg-6 mx-auto p-0 shadow">

      <div class="alert alert-warning text-center">
          <h2>Update Todo</h2>
      </div>
      
      <div class="p-4 d-flex align-items-center">
          <form action="" method="post">
              {% csrf_token %}
              {{ form.as_p }}
              <input type="submit" value="Update" class="btn btn-success" />
              <a href="{% url 'todo:home' %}"><input type="button" value="CANCEL" class="btn btn-primary"></a>
          </form>
      </div>
      
  </div>
</div> 


{% endblock content %}

    

user_example/templates/user_example/index.html
{% extends "todo/base.html" %}
{% block content %}
    

{% if user.is_authenticated %} 
<h1 style="text-align: center; color:red; margin-top: 5rem;">
    Hello {{user.username | title}}    
</h1>

<div class="d-flex justify-content-center align-items-center" style="height: 200px;">
    <a href="{% url 'todo:home' %}" class="btn btn-success btn-lg">Go to TODO page</a>
</div>

{% else %}
<h1 style="text-align: center; color:purple; margin-top: 5rem;">
    Hello, please login to see TODO_APP page.
</h1>

<div class="d-flex justify-content-center align-items-center" style="height: 200px;">
    <a href="{% url 'login' %}" class="btn btn-primary btn-lg">Go to TODO_APP</a>
</div>


{% endif %}

{% endblock content %}

user_example/templates/user_example/special.html
<h1>This is a special page!</h1>

<h3>Hello <span style="color:red;">{{ request.user }}!</span> You are lucky to see this page!</h3>